// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RSFRecomendations;

#nullable disable

namespace RSFRecomendations.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProgrammingLanguagePurposeModel", b =>
                {
                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.HasKey("ProgrammingLanguageId", "Purpose");

                    b.ToTable("ProgrammingLanguagePurpose");
                });

            modelBuilder.Entity("RSFRecomendations.Models.FormModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DifficultyForm")
                        .HasColumnType("integer");

                    b.Property<int>("ProgrammingSkillUser")
                        .HasColumnType("integer");

                    b.Property<int>("PurposeForm")
                        .HasColumnType("integer");

                    b.Property<int>("TimeEducationInWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FormModels");
                });

            modelBuilder.Entity("RSFRecomendations.Models.ProgrammingLanguageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DifficultyLanguage")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");
                });

            modelBuilder.Entity("RSFRecomendations.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RSFRecomendations.Models.UserProgrammingLanguageModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgramminLanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ProgramminLanguageId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("UserProgrammingLanguages");
                });

            modelBuilder.Entity("ProgrammingLanguagePurposeModel", b =>
                {
                    b.HasOne("RSFRecomendations.Models.ProgrammingLanguageModel", "ProgrammingLanguage")
                        .WithMany("Purposes")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("RSFRecomendations.Models.FormModel", b =>
                {
                    b.HasOne("RSFRecomendations.Models.UserModel", "User")
                        .WithOne("FormModel")
                        .HasForeignKey("RSFRecomendations.Models.FormModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSFRecomendations.Models.UserProgrammingLanguageModel", b =>
                {
                    b.HasOne("RSFRecomendations.Models.ProgrammingLanguageModel", "ProgrammingLanguage")
                        .WithMany("UsersProgrammingLanguage")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSFRecomendations.Models.UserModel", "User")
                        .WithMany("UsersProgrammingLanguage")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSFRecomendations.Models.ProgrammingLanguageModel", b =>
                {
                    b.Navigation("Purposes");

                    b.Navigation("UsersProgrammingLanguage");
                });

            modelBuilder.Entity("RSFRecomendations.Models.UserModel", b =>
                {
                    b.Navigation("FormModel")
                        .IsRequired();

                    b.Navigation("UsersProgrammingLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
