//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSFRecomendations.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSFRecomendations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camera_icon {
            get {
                object obj = ResourceManager.GetObject("camera_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить данные пользователя с пустой почтой.
        /// </summary>
        internal static string ChangeEmptyEmailLog {
            get {
                return ResourceManager.GetString("ChangeEmptyEmailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить данные пользователя с пустым логином.
        /// </summary>
        internal static string ChangeEmptyLoginLog {
            get {
                return ResourceManager.GetString("ChangeEmptyLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить данны профиля с почтой не по маске &quot;____@__.__&quot;.
        /// </summary>
        internal static string ChangeIncorrectMailLog {
            get {
                return ResourceManager.GetString("ChangeIncorrectMailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить данные пользователя с пробелами в почте.
        /// </summary>
        internal static string ChangeNoContainsSpaceEmailLog {
            get {
                return ResourceManager.GetString("ChangeNoContainsSpaceEmailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить данные пользователя с пробелами в логине.
        /// </summary>
        internal static string ChangeNoContainsSpaceLoginLog {
            get {
                return ResourceManager.GetString("ChangeNoContainsSpaceLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить данные ничего не поменяв.
        /// </summary>
        internal static string ChangeNoEditAnythingLog {
            get {
                return ResourceManager.GetString("ChangeNoEditAnythingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C++ — компилируемый язык программирования, являющийся развитием языка C и включающий поддержку объектно-ориентированного программирования. Он предоставляет программисту детальный контроль над памятью и ресурсами, что делает его одним из самых быстрых и мощных языков. Однако сложный синтаксис и высокая вероятность ошибок делают его более требовательным к опыту разработчика..
        /// </summary>
        internal static string CPlusDescription {
            get {
                return ResourceManager.GetString("CPlusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C# — объектно-ориентированный язык программирования, разработанный Microsoft. Он тесно связан с платформой .NET и предлагает мощные средства разработки для создания производительных и масштабируемых приложений. Язык отличается строгой типизацией, хорошей интеграцией с Windows-средой и отличной поддержкой инструментов разработки. Он особенно популярен в корпоративной среде и при разработке игр на Unity..
        /// </summary>
        internal static string CSharpDescription {
            get {
                return ResourceManager.GetString("CSharpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание языка.
        /// </summary>
        internal static string DescriptionLanguageText {
            get {
                return ResourceManager.GetString("DescriptionLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dislike {
            get {
                object obj = ResourceManager.GetObject("Dislike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ввдите описание языка!.
        /// </summary>
        internal static string EmptyDescriptionLang {
            get {
                return ResourceManager.GetString("EmptyDescriptionLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать язык с пустым описанием.
        /// </summary>
        internal static string EmptyDescriptionLangLog {
            get {
                return ResourceManager.GetString("EmptyDescriptionLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите сложность языка!.
        /// </summary>
        internal static string EmptyDifficultyLang {
            get {
                return ResourceManager.GetString("EmptyDifficultyLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать язык без сложности.
        /// </summary>
        internal static string EmptyDifficultyLangLog {
            get {
                return ResourceManager.GetString("EmptyDifficultyLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели почту!.
        /// </summary>
        internal static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с пустой почтой.
        /// </summary>
        internal static string EmptyEmailRegLog {
            get {
                return ResourceManager.GetString("EmptyEmailRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите изображение для языка.
        /// </summary>
        internal static string EmptyImageLang {
            get {
                return ResourceManager.GetString("EmptyImageLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать язык без изображения.
        /// </summary>
        internal static string EmptyImageLangLog {
            get {
                return ResourceManager.GetString("EmptyImageLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели логин!.
        /// </summary>
        internal static string EmptyLogin {
            get {
                return ResourceManager.GetString("EmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка входа с пустым логином.
        /// </summary>
        internal static string EmptyLoginLog {
            get {
                return ResourceManager.GetString("EmptyLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытки создания аккаунта с пустым логином.
        /// </summary>
        internal static string EmptyLoginRegLog {
            get {
                return ResourceManager.GetString("EmptyLoginRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели название языка!.
        /// </summary>
        internal static string EmptyNameLang {
            get {
                return ResourceManager.GetString("EmptyNameLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать язык без названия.
        /// </summary>
        internal static string EmptyNameLangLog {
            get {
                return ResourceManager.GetString("EmptyNameLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели пароль или ввели только пробелы!.
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка входа с пустым паролем.
        /// </summary>
        internal static string EmptyPasswordLog {
            get {
                return ResourceManager.GetString("EmptyPasswordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с пустым паролем.
        /// </summary>
        internal static string EmptyPasswordRegLog {
            get {
                return ResourceManager.GetString("EmptyPasswordRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите приоритет для языка.
        /// </summary>
        internal static string EmptyPriorityForm {
            get {
                return ResourceManager.GetString("EmptyPriorityForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка подобрать анкеты без приоритета языка.
        /// </summary>
        internal static string EmptyPriorityFormLog {
            get {
                return ResourceManager.GetString("EmptyPriorityFormLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите уровень программирвания.
        /// </summary>
        internal static string EmptyProgSkillForm {
            get {
                return ResourceManager.GetString("EmptyProgSkillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка подобрать анкету без уровня программирования.
        /// </summary>
        internal static string EmptyProgSkillFormLog {
            get {
                return ResourceManager.GetString("EmptyProgSkillFormLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите цель языка для анкеты.
        /// </summary>
        internal static string EmptyPurposeForm {
            get {
                return ResourceManager.GetString("EmptyPurposeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка подобрать анкету без цели.
        /// </summary>
        internal static string EmptyPurposeFormLog {
            get {
                return ResourceManager.GetString("EmptyPurposeFormLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите хотя бы одну цель языка!.
        /// </summary>
        internal static string EmptyPurposeLang {
            get {
                return ResourceManager.GetString("EmptyPurposeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка добавить язык без целей.
        /// </summary>
        internal static string EmptyPurposeLangLog {
            get {
                return ResourceManager.GetString("EmptyPurposeLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не ввели повторный пароль или ввели только пробелы!.
        /// </summary>
        internal static string EmptyRepeatPassword {
            get {
                return ResourceManager.GetString("EmptyRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с пустым повторным паролем.
        /// </summary>
        internal static string EmptyRepeatPasswordRegLog {
            get {
                return ResourceManager.GetString("EmptyRepeatPasswordRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите время которое хотите уделять языку.
        /// </summary>
        internal static string EmptyTimeForm {
            get {
                return ResourceManager.GetString("EmptyTimeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка подобрать анкету без времени, которое уделяется языку.
        /// </summary>
        internal static string EmptyTimeFormLog {
            get {
                return ResourceManager.GetString("EmptyTimeFormLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание.
        /// </summary>
        internal static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите почту.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите логин.
        /// </summary>
        internal static string EnterLogin {
            get {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        internal static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль повторно.
        /// </summary>
        internal static string EnterRepeatPassword {
            get {
                return ResourceManager.GetString("EnterRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь нажал кнопку перехода к добавлению языка.
        /// </summary>
        internal static string GoAddLanguageLog {
            get {
                return ResourceManager.GetString("GoAddLanguageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь нажал кнопку перехода к анкете.
        /// </summary>
        internal static string GoAnketaLog {
            get {
                return ResourceManager.GetString("GoAnketaLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go - Статически типизированный, компилируемый язык программирования, разработанный в Google (2009 г.) для создания высокопроизводительных, надежных и масштабируемых приложений..
        /// </summary>
        internal static string GoDescription {
            get {
                return ResourceManager.GetString("GoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь нажал на кнопку перехода к главному меню, до заполнения анкеты.
        /// </summary>
        internal static string GoFirstMainMenuLog {
            get {
                return ResourceManager.GetString("GoFirstMainMenuLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь нажал на кнопку перехода к главному меню.
        /// </summary>
        internal static string GoMainMenuLog {
            get {
                return ResourceManager.GetString("GoMainMenuLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь нажал кнопку перехода к профилю.
        /// </summary>
        internal static string GoProfileLog {
            get {
                return ResourceManager.GetString("GoProfileLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь нажал кнопку перехода к языкам программирования.
        /// </summary>
        internal static string GoProgLangLog {
            get {
                return ResourceManager.GetString("GoProgLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить логин на некорректный.
        /// </summary>
        internal static string IncorrectEditLoginLog {
            get {
                return ResourceManager.GetString("IncorrectEditLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин может содержать только латиницу и цифры и должен состоять минимум из 3 символов.
        /// </summary>
        internal static string IncorrectLogin {
            get {
                return ResourceManager.GetString("IncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать аккаунт с некорректным логином.
        /// </summary>
        internal static string IncorrectLoginLog {
            get {
                return ResourceManager.GetString("IncorrectLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта должна быть вида &quot;____@__.__&quot; и до @ должно быть минимум 4 символа, после @ и до . минимум 3 символа, после . минимум 2 символа.
        /// </summary>
        internal static string IncorrectMail {
            get {
                return ResourceManager.GetString("IncorrectMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с почтой не по маске &quot;____@__.__&quot;.
        /// </summary>
        internal static string IncorrectMailLog {
            get {
                return ResourceManager.GetString("IncorrectMailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Java — строго типизированный объектно-ориентированный язык, работающий через виртуальную машину (JVM), что обеспечивает его кроссплатформенность. Он известен своей надёжностью, безопасностью и масштабируемостью, что делает его популярным выбором для разработки больших и долгоживущих программных систем. Несмотря на многословность синтаксиса, Java сохраняет стабильную популярность в корпоративной среде..
        /// </summary>
        internal static string JavaDescription {
            get {
                return ResourceManager.GetString("JavaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на JavaScript — интерпретируемый язык программирования, выполняемый в основном в браузере. Он динамически типизируется, поддерживает как объектно-ориентированный, так и функциональный стиль программирования, и является неотъемлемой частью веб-разработки. Благодаря обширной экосистеме и низкому порогу входа, JavaScript широко используется, но его гибкость может привести к неустойчивому коду без соблюдения строгих стандартов..
        /// </summary>
        internal static string JavaScriptDescription {
            get {
                return ResourceManager.GetString("JavaScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание языка.
        /// </summary>
        internal static string LanguageDescriptionInfo {
            get {
                return ResourceManager.GetString("LanguageDescriptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сложность языка.
        /// </summary>
        internal static string LanguageDifficultyInfo {
            get {
                return ResourceManager.GetString("LanguageDifficultyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цели языка.
        /// </summary>
        internal static string LanguagePurposeInfo {
            get {
                return ResourceManager.GetString("LanguagePurposeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В пароле должно быть минимум 8 символов!.
        /// </summary>
        internal static string LengthPassword {
            get {
                return ResourceManager.GetString("LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с паролем, у которого меньше 8 символов.
        /// </summary>
        internal static string LengthPasswordRegLog {
            get {
                return ResourceManager.GetString("LengthPasswordRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Like {
            get {
                object obj = ResourceManager.GetObject("Like", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainMenuFirst {
            get {
                object obj = ResourceManager.GetObject("MainMenuFirst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainMenuFirstLog {
            get {
                object obj = ResourceManager.GetObject("MainMenuFirstLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название языка.
        /// </summary>
        internal static string NameLanguageText {
            get {
                return ResourceManager.GetString("NameLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В описании языка не должны быть пробелы.
        /// </summary>
        internal static string NoContainsSpaceDescriptionLang {
            get {
                return ResourceManager.GetString("NoContainsSpaceDescriptionLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать язык с пробелами в описании.
        /// </summary>
        internal static string NoContainsSpaceDescriptionLangLog {
            get {
                return ResourceManager.GetString("NoContainsSpaceDescriptionLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почта не может содержать пробелы!.
        /// </summary>
        internal static string NoContainsSpaceEmail {
            get {
                return ResourceManager.GetString("NoContainsSpaceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя не может содержать пробелы!.
        /// </summary>
        internal static string NoContainsSpaceLogin {
            get {
                return ResourceManager.GetString("NoContainsSpaceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка входа с пробелами в логине.
        /// </summary>
        internal static string NoContainsSpaceLoginLog {
            get {
                return ResourceManager.GetString("NoContainsSpaceLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с пробелами в логине.
        /// </summary>
        internal static string NoContainsSpaceLoginRegLog {
            get {
                return ResourceManager.GetString("NoContainsSpaceLoginRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название языка не может содержать пробелы.
        /// </summary>
        internal static string NoContainsSpaceNameLang {
            get {
                return ResourceManager.GetString("NoContainsSpaceNameLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания языка с пробелами в названии.
        /// </summary>
        internal static string NoContainsSpaceNameLangLog {
            get {
                return ResourceManager.GetString("NoContainsSpaceNameLangLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль не может содержать пробелы!.
        /// </summary>
        internal static string NoContainsSpacePassword {
            get {
                return ResourceManager.GetString("NoContainsSpacePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторный пароль не может содержать пробелы!.
        /// </summary>
        internal static string NoContainsSpacePassword2 {
            get {
                return ResourceManager.GetString("NoContainsSpacePassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с пробелами в повторном пароле.
        /// </summary>
        internal static string NoContainsSpacePassword2RegLog {
            get {
                return ResourceManager.GetString("NoContainsSpacePassword2RegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка входа с пробелами в пароле.
        /// </summary>
        internal static string NoContainsSpacePasswordLog {
            get {
                return ResourceManager.GetString("NoContainsSpacePasswordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с пробелами в пароле.
        /// </summary>
        internal static string NoContainsSpacePasswordRegLog {
            get {
                return ResourceManager.GetString("NoContainsSpacePasswordRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ничего не изменили!.
        /// </summary>
        internal static string NoEditAnything {
            get {
                return ResourceManager.GetString("NoEditAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В вашей почте нет специального символа @ !.
        /// </summary>
        internal static string NotSobachkaInEmail {
            get {
                return ResourceManager.GetString("NotSobachkaInEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователя с таким логином не существует!.
        /// </summary>
        internal static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка входа с несуществующим логином.
        /// </summary>
        internal static string NoUserLog {
            get {
                return ResourceManager.GetString("NoUserLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши пароли не совпадают!.
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создания аккаунта с не правильным повторяющим паролем.
        /// </summary>
        internal static string PasswordsDontMatchRegLog {
            get {
                return ResourceManager.GetString("PasswordsDontMatchRegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Python — это высокоуровневый интерпретируемый язык программирования, известный своей простотой, читаемым синтаксисом и широкой областью применения. Он идеально подходит для быстрого прототипирования, написания скриптов и автоматизации. Благодаря огромному количеству библиотек и активному сообществу, Python часто используется в научной среде, бизнесе и стартапах. Несмотря на универсальность, его скорость исполнения ниже, чем у компилируемых языков..
        /// </summary>
        internal static string PythonDescription {
            get {
                return ResourceManager.GetString("PythonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Register {
            get {
                object obj = ResourceManager.GetObject("Register", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторная анкета успешна заполнена.
        /// </summary>
        internal static string SuccessfulEditForm {
            get {
                return ResourceManager.GetString("SuccessfulEditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения успешно сохранены!.
        /// </summary>
        internal static string SuccessfulEditProfile {
            get {
                return ResourceManager.GetString("SuccessfulEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анкета успешно заполнена.
        /// </summary>
        internal static string SuccessfulForm {
            get {
                return ResourceManager.GetString("SuccessfulForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык успешно добавлен.
        /// </summary>
        internal static string SuccessfullyAddedLanguage {
            get {
                return ResourceManager.GetString("SuccessfullyAddedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация прошла успешна!.
        /// </summary>
        internal static string SuccessfulRegistration {
            get {
                return ResourceManager.GetString("SuccessfulRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TeamRSF {
            get {
                object obj = ResourceManager.GetObject("TeamRSF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык с таким названием уже существует.
        /// </summary>
        internal static string TheLanguageAlreadyExists {
            get {
                return ResourceManager.GetString("TheLanguageAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка добавить существующий язык.
        /// </summary>
        internal static string TheLanguageAlreadyExistsLog {
            get {
                return ResourceManager.GetString("TheLanguageAlreadyExistsLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить почту на уже существующую.
        /// </summary>
        internal static string UserExistsEmailToEdit {
            get {
                return ResourceManager.GetString("UserExistsEmailToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка изменить логин на уже существующий.
        /// </summary>
        internal static string UserExistsLoginToEdit {
            get {
                return ResourceManager.GetString("UserExistsLoginToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с такой почтой уже существует.
        /// </summary>
        internal static string UserExistsRegEmail {
            get {
                return ResourceManager.GetString("UserExistsRegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать аккаунт уже с существующей почтой.
        /// </summary>
        internal static string UserExistsRegEmailLog {
            get {
                return ResourceManager.GetString("UserExistsRegEmailLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже сущетсвует!.
        /// </summary>
        internal static string UserExistsRegLogin {
            get {
                return ResourceManager.GetString("UserExistsRegLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка создать аккаунт уже с существующим логином.
        /// </summary>
        internal static string UserExistsRegLoginLog {
            get {
                return ResourceManager.GetString("UserExistsRegLoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы ввели не правильный пароль!.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка входа с не правильным паролем.
        /// </summary>
        internal static string WrongPasswordLog {
            get {
                return ResourceManager.GetString("WrongPasswordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Аватарка {
            get {
                object obj = ResourceManager.GetObject("Аватарка", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Снимок_экрана_2025_05_03_192332 {
            get {
                object obj = ResourceManager.GetObject("Снимок экрана 2025-05-03 192332", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Снимок_экрана_2025_05_03_192336 {
            get {
                object obj = ResourceManager.GetObject("Снимок экрана 2025-05-03 192336", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
